spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: Monu@281611
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  server:
    port: 8082